<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admission Date' => '',
    'Bonus' => '',
    'Class Group ID' => '',
    'Code' => '',
    'Coefficient' => '',
    'Course ID' => '',
    'Credit' => '',
    'Date' => '',
    'Date Of Birth' => '',
    'Designation' => '',
    'Educational Unit ID' => '',
    'First Name' => '',
    'Grade ID' => '',
    'Instructor ID' => '',
    'Last Name' => '',
    'Level ID' => '',
    'Moral Person ID' => '',
    'Nature' => '',
    'Number' => '',
    'Option' => '',
    'Place Of Birth' => '',
    'Registration Number' => '',
    'Section ID' => '',
    'Section Name' => '',
    'Semester' => '',
    'Student ID' => '',
    'User ID' => '',
    'Value' => '',
    'Year' => '',
];
